version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

executors:
  default:
    docker:
      - image: 'cimg/node:8.17'
      - image: 'cimg/python:3.6'

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install node dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  npm_test:
    steps:
      - run:
          name: run unit test
          command: yarn test
  npm_build:
    steps:
      - run:
          name: build app
          command: yarn build

jobs:
  build:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
  
  test:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - npm_test
      
  deploy:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - run:
          name: build
          command: yarn build
      - aws-s3/sync:
          from: dist
          to: s3://${S3_BUCKET}
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
