version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:8.17

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install node dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  npm_test:
    steps:
      - run:
          name: run unit test
          command: yarn test

jobs:
  build:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
  
  test:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_test
      
  deploy:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - run:
          name: build
          command: yarn build:prod
      - aws-s3/sync:
          from: dist
          to: s3://<S3 Bucket Name>
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
